// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewGraphQL.Data;

#nullable disable

namespace NewGraphQL.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    [Migration("20240101100406_SeedMenusTbl")]
    partial class SeedMenusTbl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewGraphQL.Model.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = " very clasy burger",
                            Name = "Classic Burger",
                            Price = 39.890000000000001
                        },
                        new
                        {
                            Id = 2,
                            Description = " very buttery burger",
                            Name = "Butter Burger",
                            Price = 49.890000000000001
                        },
                        new
                        {
                            Id = 3,
                            Description = " very cheesy burger",
                            Name = "Cheese Burger",
                            Price = 59.890000000000001
                        },
                        new
                        {
                            Id = 4,
                            Description = " Samosa Inside burger",
                            Name = "Samosa Burger",
                            Price = 69.890000000000001
                        },
                        new
                        {
                            Id = 5,
                            Description = " Paneer inisde burger",
                            Name = "Paneer Burger",
                            Price = 89.890000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
